### PR TITLE
fix: guess file extension from preset

### LINKED ISSUE #1666: Include file extension in REPL config options
With https://github.com/babel/babel/pull/7955 Babel now allows both the flow and typescript presets to be used in parallel, and allows JSX only in `.tsx`, not `.ts` files. Given that, we'll want to stop hard-coding the filename "repl" with no extension in https://github.com/babel/website/blob/71a346f6ab95047b9c6a1df373aca5b9dc609501/js/repl/compile.js#L84

Including the extension is important now, so the UI should expose that as well.

### PR DESCRIPTION
**Pull request by JLHwung**
In this PR we guess the REPL file extension from the loaded presets. By doing so we could apply proper TypeScript transform when `typescript` preset is enabled.

Compared to #2019, this PR does _not_ introduce `filename` option as we don't output error message that will point to `filename` configuration when parsing a TypeScript without transform enabled. Also we are not going to expose `filename` option in a such limited UI space.

Manually tested on local build.

Closes #2019 
Fixes #1666

### CODE REVIEW

File: js/repl/types.js [hunk 1]
```diff
@@ -141,3 +141,5 @@ export type Transition = {
   visitorType: string,
   currentNode?: string,
 };
+
+export type SupportedFileExtension = ".js" | ".jsx" | ".ts" | ".tsx";
```
Comment (JLHwung) [inline js/repl/types.js]: Do we need `.mjs` when `config.sourceType === "module"`?

Comment (xtuc) [reply js/repl/types.js]: That would be more consistent with the Node.js experience, I would say yes.

Comment (nicolo-ribaudo) [reply js/repl/types.js]: Well, it isn't observable to users.

Comment (JLHwung) [reply js/repl/types.js]: True. Given that we don't have `.mjs` specific transforms in the preset, we don't have to add it here.
