### PR TITLE
Fix minify/evaluate options in REPL

### LINKED ISSUE #1446: `evaluate` doesn't work
Go to https://babeljs.io/repl in Chrome.
Click on `evaluate`.

Nothing happens. The checkbox is not toggled to checked and it has no effect.

### PR DESCRIPTION
**Pull request by existentialism**
Fixes #1446.

I'm also finishing a refactor/cleanup PR for all this config.package/config.label checking we have everywhere now :(

### CODE REVIEW

File: js/repl/PluginConfig.js [hunk 1]
```diff
@@ -25,7 +25,7 @@ const envPresetDefaults = {
 };
 
 const runtimePolyfillConfig: PluginConfig = {
-  label: "Runtime Poylfill",
+  label: "Runtime Polyfill",
```
Comment (existentialism) [inline js/repl/PluginConfig.js]: Note: this isn't a huge deal, since it's unused, was just bothering me :)

**Comment by xtuc** [comment]
thanks @existentialism
