### PR TITLE
Fix cm error on assumptions

### LINKED ISSUE #2456: Assumptions page examples aren't loading
Hello there

On https://babeljs.io/assumptions the examples under each rule don't load, tested in firefox and chrome

image

Console shows these errors, repeated ~20 times each

```
state.js:864 Uncaught TypeError: Cannot read property 'extension' of undefined
    at inner (state.js:864)
    at inner (state.js:864)
    at inner (state.js:847)
    at inner (state.js:864)
    at inner (state.js:847)
    at flatten (state.js:867)
    at Function.resolve (state.js:786)
    at Function.create (state.js:1262)
    at HTMLElement._createInputEditorState (mini-repl.js:217)
    at HTMLElement.connectedCallback (mini-repl.js:160)
inner @ state.js:864
inner @ state.js:864
inner @ state.js:847
inner @ state.js:864
inner @ state.js:847
flatten @ state.js:867
resolve @ state.js:786
create @ state.js:1262
_createInputEditorState @ mini-repl.js:217
connectedCallback @ mini-repl.js:160
AssumptionDocs @ assumption-docs.js:23
(anonymous) @ assumption-docs.js:54
```

```
mini-repl.js:182 Uncaught TypeError: Cannot read property 'setState' of undefined
    at HTMLElement.setInput (mini-repl.js:182)
    at new AssumptionDocs (assumption-docs.js:29)
    at assumption-docs.js:54
setInput @ mini-repl.js:182
AssumptionDocs @ assumption-docs.js:29
(anonymous) @ assumption-docs.js:54
```

### PR DESCRIPTION
**Pull request by JLHwung**
Fixes #2456 

Use pre-built code mirror 6 since there are bundling issues in skypack.dev (https://github.com/babel/website/issues/2456#issuecomment-784245936)

### CODE REVIEW

File: website/static/js/components/mini-repl.js [hunk 1]
```diff
@@ -1,13 +1,21 @@
 /* globals Babel */
 
-import debounce from "https://cdn.skypack.dev/lodash-es/debounce";
+import debounce from "https://cdn.skypack.dev/pin/lodash-es@v4.17.21-rDGl8YjBUjcrrAbjNrmo/mode=imports,min/unoptimized/debounce.js";
```
Comment (JLHwung) [inline website/static/js/components/mini-repl.js:3]: Pin `loadsh-debounce` to an optimized minified specific option to prevent breaking changes.

**Review by nicolo-ribaudo — APPROVED** [review]
https://deploy-preview-2457--babel.netlify.app/assumptions

Syntax highlighting is back!

**Review by kaicataldo — APPROVED** [review]
🎉
